version: '3'

services:
  web-back:
    build: ./backend/.
    ports:
      - "5000:5000"
    volumes:
      - ./backend/db.json:/data/db.json
    command: json-server --watch /data/db.json --port 5000 --host 0.0.0.0

  web-front:
    build: ./frontend/.
    ports:
      - "80:80"