# STEP 1 BUILD dist
FROM node:18-alpine
RUN npm install -g json-server
WORKDIR /data
EXPOSE 5000

#FROM node:18-alpine
#WORKDIR /data
#COPY package.json .
#RUN npm install
#COPY . .
#EXPOSE 5000
#CMD ["npm","start"]